# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-14.27
packages:
- .
#- ../IHaskell/ihaskell-display/ihaskell-diagrams
#- ../IHaskell/ihaskell-display/ihaskell-juicypixels
extra-deps:
- hlint-2.1.17
- hip-1.5.4.0
