# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-12.16
packages:
- .
- ../IHaskell/ihaskell-display/ihaskell-diagrams
- ../IHaskell/ihaskell-display/ihaskell-juicypixels
extra-deps:
- ../fei-nn
- ../fei-base
- ../tuple-ops
- git: https://github.com/kylcarte/type-combinators.git
  commit: 071942730b6bb34990d37e1a25236382cf0dcbc6
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- c2hs-extra-0.1.0.1
    #- streaming-utils-0.1.4.7
    #- graphviz-2999.20.0.2
    #- fgl-5.5.4.0
- JuicyPixels-repa-0.7.1.0
- hlint-2.1.17
- haskell-src-exts-util-0.2.5
- unordered-containers-0.2.10.0
- glib-0.13.7.1
- pango-0.13.6.1
- conduit-concurrent-map-0.1.1
- hip-1.5.4.0
- Chart-1.9
- Chart-diagrams-1.9
- SVGFonts-1.6.0.3
extra-include-dirs:
- /home/jiasen/hdd/dschungel/incubator-mxnet-1.6.0.rc1/include
extra-lib-dirs:
- /home/jiasen/hdd/dschungel/incubator-mxnet-1.6.0.rc1/lib
flags:
  fei-base:
    MXNet_1_6: true
